# Generated by Django 6.0.5 on 2026-05-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_payment', 'En attente de paiement'), ('published', 'Publié'), ('closed', 'Fermé'), ('removed', 'Retiré')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mvola', 'MVola'), ('orange', 'Orange Money'), ('airtel', 'Airtel Money')], max_length=20)),
                ('amount_mga', models.PositiveIntegerField()),
                ('msisdn', models.CharField(max_length=20)),
                ('internal_reference', models.CharField(max_length=64, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.offer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_reference'], name='api_payment_provide_ca645a_idx'), models.Index(fields=['status', 'created_at'], name='api_payment_status_268a01_idx')],
            },
        ),
    ]
