# Generated by Django 6.0.5 on 2026-05-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_offer_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='contact_method',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='description_short',
        ),
    ]
