# Generated by Django 6.0.5 on 2026-05-07 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('internship', 'Stage'), ('volunteer', 'Volontariat')], default='internship', max_length=20)),
                ('domain', models.CharField(max_length=120)),
                ('description_short', models.CharField(max_length=300)),
                ('description_full', models.TextField(blank=True)),
                ('tasks', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('experience_required', models.PositiveSmallIntegerField(default=0)),
                ('experience_justification', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Sur site'), ('hybrid', 'Hybride')], default='onsite', max_length=20)),
                ('contact_method', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('closed', 'Fermé'), ('removed', 'Retiré')], default='draft', max_length=20)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('viewed', 'Vu'), ('archived', 'Archivé')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.offer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offer', 'email', 'created_at'], name='api_applica_offer_i_095a62_idx'), models.Index(fields=['email', 'created_at'], name='api_applica_email_006603_idx')],
            },
        ),
    ]
