# Generated by Django 6.0.5 on 2026-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_offer_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruteur'), ('candidate', 'Candidat')], default='recruiter', max_length=20),
        ),
    ]
